# Generated by Django 2.2.10 on 2020-06-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersIIN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='IIN',
            field=models.IntegerField(),
        ),
    ]
